### ISSUE TITLE
Lol what

### ISSUE THREAD

**Issue by ORESoftware** [thlorenz/dev-null#1]
Does this really pipe to /dev/null

https://github.com/thlorenz/dev-null/blob/master/index.js

or do you just have an empty write function? I am confused

**Comment by thlorenz** [comment]
Just have a look at the code, it's rather short ;)

**Comment by ORESoftware** [comment]
yeah I did before :) I just didn't see any reference to the path '/dev/null' so I guess I am mystified by even 10 lines of code :)

**Comment by ORESoftware** [comment]
Ok so what you're saying is it's an empty _write function

```
DevNull.prototype._write = function (chunk, encoding, cb) {
  setImmediate(cb);
}
```

isn't that misleading then?
